# Generated by Django 3.0.2 on 2020-02-18 08:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_images_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
