# Generated by Django 3.0.2 on 2020-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20200120_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Mobile_no',
            field=models.IntegerField(),
        ),
    ]
