# Generated by Django 3.0.2 on 2020-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_auto_20200120_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AG', 'Agent'), ('AD', 'Admin'), ('EV', 'Evaluator'), ('ST', 'STL'), ('AC', 'Accountent')], max_length=2),
        ),
    ]
