# Generated by Django 3.0.2 on 2020-01-24 05:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DustLevelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dust_level', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('open', 'Open Process'), ('in_evaluation', 'In Evaluation Process'), ('evaluation_done', 'Evaluation Done'), ('in_stl', 'In STL Observation'), ('in_tl', 'In TL Observation'), ('in_payment', 'In Payment Process'), ('order_done', 'Order Done')], max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 24, 5, 47, 32, 544686, tzinfo=utc))),
                ('unique_id', models.CharField(max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_pk', to='customer.Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('open', 'Open'), ('in_process', 'In Process'), ('finish', 'Finish')], max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 1, 24, 5, 47, 32, 545321, tzinfo=utc))),
                ('evaluation_date', models.DateTimeField(default=datetime.datetime(2020, 1, 24, 5, 47, 32, 545342, tzinfo=utc))),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('service_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderTask')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ManyToManyField(to='owners.TeamMembers')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Services'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members', models.IntegerField()),
                ('expected_time', models.FloatField()),
                ('estimated_price', models.FloatField()),
                ('dust_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DustLevelPrice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pk', to='order.Order')),
                ('order_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderTask')),
            ],
        ),
    ]
