# Generated by Django 3.0.2 on 2020-01-24 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 6, 34, 35, 444345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 6, 34, 35, 444965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 6, 34, 35, 444986, tzinfo=utc)),
        ),
    ]
