# Generated by Django 3.0.2 on 2020-01-24 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200124_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 5, 43, 667084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 5, 43, 667819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 5, 43, 667840, tzinfo=utc)),
        ),
    ]
