# Generated by Django 3.0.2 on 2020-01-23 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200122_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='no_of_team_members',
            new_name='team_members',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 12, 13, 47, 67259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.CharField(choices=[('open', 'Open Process'), ('in_evaluation', 'In Evaluation Process'), ('evaluation_done', 'Evaluation Done'), ('in_stl', 'In STL Observation'), ('in_tl', 'In TL Observation'), ('in_payment', 'In Payment Process'), ('order_done', 'Order Done')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 12, 13, 47, 67954, tzinfo=utc)),
        ),
    ]
