# Generated by Django 3.0.2 on 2020-01-24 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200124_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 24, 42, 892553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 24, 42, 893302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 7, 24, 42, 893325, tzinfo=utc)),
        ),
    ]
