# Generated by Django 3.0.2 on 2020-01-24 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200124_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordertask',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordertask',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordertask',
            name='schedule_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 8, 44, 38, 379584, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ordertask',
            name='schedule_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 8, 44, 38, 379567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 8, 44, 38, 378742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 8, 44, 38, 379527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 8, 44, 38, 379550, tzinfo=utc)),
        ),
    ]
