# Generated by Django 3.0.2 on 2020-01-24 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200124_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 11, 47, 52, 43185, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 11, 47, 52, 43962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 11, 47, 52, 43988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='schedule_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='schedule_on',
            field=models.DateTimeField(null=True),
        ),
    ]
