# Generated by Django 3.0.2 on 2020-01-24 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200124_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertask',
            name='evaluation_date',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 13, 42, 40, 648824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 13, 42, 40, 647410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 13, 42, 40, 648155, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='schedule_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 13, 42, 40, 648195, tzinfo=utc)),
        ),
    ]
