# Generated by Django 3.0.2 on 2020-01-27 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200124_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 5, 38, 37, 708008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 5, 38, 37, 706594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.CharField(choices=[('in_evaluation', 'In Evaluation Process'), ('evaluation_done', 'Evaluation Done'), ('in_stl', 'In STL Observation'), ('stl_done', 'STL Process Done'), ('in_tl', 'In TL Observation'), ('tl_done', 'TL Process Done'), ('in_payment', 'In Payment Process'), ('order_done', 'Order Done')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 5, 38, 37, 707334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='process',
            field=models.CharField(choices=[('in_process', 'In Process'), ('finish', 'Finish')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='schedule_end',
            field=models.DateTimeField(null=True),
        ),
    ]
