# Generated by Django 3.0.2 on 2020-01-27 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200127_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 11, 10, 23, 769994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 11, 10, 23, 769474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 11, 10, 23, 768021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 11, 10, 23, 768771, tzinfo=utc)),
        ),
    ]
