# Generated by Django 3.0.2 on 2020-01-28 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200127_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='order_task',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator_order_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_order_task', to='order.OrderTask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stl_order_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stl_order_task', to='order.OrderTask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 5, 57, 419966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 5, 57, 418488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 5, 57, 419234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 5, 57, 420529, tzinfo=utc)),
        ),
    ]
