# Generated by Django 3.0.2 on 2020-01-28 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200128_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 39, 51, 473603, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='expected_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 39, 51, 472156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 39, 51, 472898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 7, 39, 51, 474164, tzinfo=utc)),
        ),
    ]
