# Generated by Django 3.0.2 on 2020-01-29 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200128_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertask',
            name='description',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 9, 16, 29, 823814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 9, 16, 29, 822368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 9, 16, 29, 823124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 9, 16, 29, 824391, tzinfo=utc)),
        ),
    ]
