# Generated by Django 3.0.2 on 2020-01-31 07:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0015_auto_20200130_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 7, 0, 36, 951820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 7, 0, 36, 950347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 7, 0, 36, 951116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 7, 0, 36, 952450, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 7, 0, 36, 953728, tzinfo=utc))),
                ('end', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 7, 0, 36, 953749, tzinfo=utc))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('order_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderTask')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Team')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
