# Generated by Django 3.0.2 on 2020-01-31 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200131_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 1, 33, 681554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 1, 33, 680058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 1, 33, 680838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 1, 33, 682202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 9, 1, 33, 683484, tzinfo=utc)),
        ),
    ]
