# Generated by Django 3.0.2 on 2020-02-03 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200203_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 29, 27, 252799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 29, 27, 250379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 29, 27, 248914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 29, 27, 249669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 29, 27, 251004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 29, 27, 252246, tzinfo=utc)),
        ),
    ]
