# Generated by Django 3.0.2 on 2020-02-03 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20200203_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 34, 18, 947623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 34, 18, 945022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 34, 18, 943487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 34, 18, 944288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 34, 18, 945689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 34, 18, 947030, tzinfo=utc)),
        ),
    ]
