# Generated by Django 3.0.2 on 2020-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_evaluation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='img',
            field=models.ImageField(null=True, upload_to='evaluation/'),
        ),
    ]
