# Generated by Django 3.0.2 on 2020-02-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_evaluation_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='evaluation/')),
                ('is_evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Evaluation')),
            ],
        ),
    ]
