# Generated by Django 3.0.2 on 2020-02-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_evaluationmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationmedia',
            old_name='img',
            new_name='image',
        ),
    ]
