# Generated by Django 3.0.2 on 2020-02-18 06:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20200213_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=django_fsm.FSMField(choices=[('in_evaluation', 'In Evaluation Process'), ('evaluation_done', 'Evaluation Done'), ('in_stl', 'In STL Observation'), ('stl_done', 'STL Process Done'), ('in_cleaning', 'In Cleaning Process'), ('cleaning_done', 'Cleaning Process Done'), ('in_payment', 'In Payment Process'), ('order_done', 'Order Done')], default='in_evaluation', max_length=50),
        ),
    ]
