# Generated by Django 3.0.2 on 2020-02-18 08:44

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20200218_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=django_fsm.FSMField(choices=[('in_evaluation', 'In Evaluation Process'), ('evaluation_done', 'Evaluation Done'), ('in_stl', 'In STL Observation'), ('in_customer', 'In Customer Acceptance'), ('customer_rejected', 'Customer Rejected'), ('customer_accepted', 'Customer Accepted'), ('in_cleaning', 'In Cleaning Process'), ('cleaning_done', 'Cleaning Process Done'), ('in_payment', 'In Payment Process'), ('order_done', 'Order Done')], default='in_evaluation', max_length=50),
        ),
    ]
