# Generated by Django 3.0.2 on 2020-01-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
